//HintName: ValidateOptionsAttribute.g.cs
// <auto-generated>
//     Automatically generated by Koncq.OptionsValidation.
//     Changes made to this file may be lost and may cause undesirable behaviour.
// </auto-generated>
#nullable enable

namespace Koncq.OptionsValidation
{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public class ValidateOptionsAttribute : System.Attribute
    {
        public string? SectionName { get; set; }
        public bool SkipStartupValidation { get; set; }
    }
}