//HintName: OptionsValidationExtensions.g.cs
// <auto-generated>
//     Automatically generated by Koncq.OptionsValidation.
//     Changes made to this file may be lost and may cause undesirable behaviour.
// </auto-generated>
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Koncq.OptionsValidation 
{
    public static partial class OptionsValidationExtension
    {
        public static IServiceCollection RegisterOptions(this IServiceCollection serviceCollection, IConfiguration configuration)
        {
            serviceCollection
                .AddOptions<Example>()
                .Bind(configuration.GetSection("Example"))
                .ValidateDataAnnotations()
                .ValidateOnStart();

            return serviceCollection;
        }
    }
}